### ISSUE TITLE
Events disappear if set to "all day"

### ISSUE THREAD

**Issue by vmario89** [berrnd/shareical#1]
Hi,
this tool is neat. Testing it and found a first issue which i dont see to fix with an option. If an event has no specific start/end time its just ignored /not rendered

**Comment by vmario89** [comment]
add: also does not render if the event has no place where to happen

**Comment by berrnd** [comment]
Sorry, but this is more than outdated and not actively maintained (and neither used by myself) for a couple of years now - the repository will be archived.
